plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
    alias(libs.plugins.kotlin.compose)
}

android {
    compileSdkVersion 36
    buildToolsVersion "34.0.0"
    namespace 'dev.jeziellago.compose.markdown'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        compose true
    }
    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.12'
    }
    
    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE.md', 'META-INF/LICENSE-notice.md']
        }
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat

    final def markwon_version = '4.6.2'

    implementation "io.noties.markwon:core:$markwon_version"
    implementation "io.noties.markwon:ext-strikethrough:$markwon_version"
    implementation "io.noties.markwon:ext-tables:$markwon_version"
    implementation "io.noties.markwon:html:$markwon_version"
    implementation "io.noties.markwon:linkify:$markwon_version"
    implementation "io.noties.markwon:ext-tasklist:$markwon_version"

    // TODO: Change it after migrating markwon project
    implementation "com.github.jeziellago:Markwon:58aa5aba6a"

    api libs.coil
    api libs.coil.network.okhttp
    api("io.coil-kt.coil3:coil-gif:3.3.0")

    // Jetpack Compose
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.material3
    
    // Testing dependencies
    testImplementation libs.junit
    testImplementation 'org.mockito:mockito-core:5.1.1'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:4.1.0'
    testImplementation libs.robolectric
    testImplementation 'androidx.test:core:1.5.0'
    testImplementation 'androidx.test.ext:junit:1.1.5'
    testImplementation libs.mockk
    testImplementation libs.kotlinx.coroutines.test

    // Android Instrumentation Tests
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation 'androidx.test:rules:1.5.0'
    androidTestImplementation libs.androidx.compose.ui
    androidTestImplementation libs.androidx.compose.ui
    androidTestImplementation 'io.mockk:mockk-android:1.13.5'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                groupId = 'dev.jeziellago'
                artifactId = 'compose-markdown'
                version = library_version
            }
        }
    }
}
